### PR TITLE
Dotnetcore

### LINKED ISSUE #27: Add support for .NET Core
There are some use cases we're developing where .NETCore support is required.  I'll be submitted a related PR with the necessary changes.  These will be able to live side-by-side with existing code.

### PR DESCRIPTION
**Pull request by rgmills**
Add support for .NET Core targeting NETStandard 1.3.  Resolves #27

### CODE REVIEW

**Comment by AjmalVh** [comment]
I will check this and merge. Are you able to test this?

**Comment by rgmills** [comment]
Going to have to move the project.json / .xproj bits to it's own folder.  I forgot that the `dotnet pack` command infers package name from the folder containing the package.

**Comment by rgmills** [comment]
@AjmalVh Yep, able to test.  Log in, create a few items, fetch application, etc.

**Comment by AjmalVh** [comment]
Thank you for your pull request. I have merged it. Will update the nuget package after internal testing.

**Pull request merged**
