### PR TITLE
item_revision_id updated to long

### PR DESCRIPTION
**Pull request by PavloBasiuk**

### CODE REVIEW

**Comment by PavloBasiuk** [comment]
I'd recommend to build from master.

**Comment by steveglen** [comment]
@PavloBasiuk master appears to only contain an async API which is not the same as the Podio package https://www.nuget.org/packages/Podio/1.5.6

Can you confirm if this package is built from the v1 branch, and Podio.Async is built from the master branch?

Please ask the people updating status.podio.com to clarify what's changed to fix this issue, to help other consumers of the API to fix their apps.

**Comment by Denacke** [comment]
I built from the v1 branch with the changed int -> long and it worked as a drop in replacement for the nuget package in our solution.

**Comment by steveglen** [comment]
building from v1 and applying the same change also seems to work for me as a drop in replacement for the nuget Podio package.

**Comment by PavloBasiuk** [comment]
Thanks for confirming!

**Pull request merged**
